services:
  - type: web
    name: flixnest-scraper
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
